[build]

base = "."

command = "npm run build:prod"

publish = "dist/browser"

[[redirects]]

from = "/*"

to = "dist/browser/en-US/index.html"

status = 200

[[plugins]]
  package = "@netlify/angular-runtime"
